import { GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";
import Layout from "../../components/_shared/Layout";
import Tabs from "../../components/_shared/Tabs";
import TopBar from "../../components/_shared/TopBar";
import PaginatedDatasetSection from "../../components/_shared/PaginatedDatasetSection";
import PaginatedActivityStream from "../../components/_shared/PaginatedActivityStream";
import { CKAN, Group } from "@portaljs/ckan";
import styles from "@/styles/DatasetInfo.module.scss";
import GroupNavCrumbs from "../../components/groups/individualPage/GroupNavCrumbs";
import GroupInfo from "../../components/groups/individualPage/GroupInfo";
import { getActivityStreamPage } from "@/lib/queries/activity";
import { trimDatasetCardData } from "@/lib/queries/pageData";
import { getAllGroups, getGroup } from "@/lib/queries/groups";
import { searchGroupDatasets } from "@/lib/queries/dataset";

const DATASETS_PER_PAGE = 10;
const ACTIVITY_PAGE_SIZE = 20;

export async function getStaticPaths() {
  const paths = (await getAllGroups({ detailed: false })).map(
    (group: Group) => ({
      params: { groupName: group.name },
    })
  );
  return {
    paths,
    fallback: "blocking",
  };
}

export const getStaticProps: GetStaticProps = async (context) => {
  const DMS = process.env.NEXT_PUBLIC_DMS;
  const ckan = new CKAN(DMS);
  const groupName = context.params?.groupName;
  if (!groupName) {
    return {
      notFound: true,
    };
  }
  let group = await getGroup({
    name: groupName as string,
  });
  const packageSearch = await searchGroupDatasets({
    group: groupName as string,
    offset: 0,
    limit: DATASETS_PER_PAGE,
  });
  group = {
    ...group,
    package_count: packageSearch.count,
    packages: trimDatasetCardData(packageSearch.datasets),
  };
  if (!group) {
    return {
      notFound: true,
    };
  }
  const activityStream = await getActivityStreamPage({
    entityId: group._name,
    entityType: "group",
    limit: ACTIVITY_PAGE_SIZE,
    offset: 0,
  });
  group = {
    ...group,
    activity_stream: activityStream.activities,
    activity_stream_has_more: activityStream.hasMore,
  };
  return {
    props: {
      group,
    },
    revalidate: 1800,
  };
};

export default function OrgPage({
  group,
}: InferGetStaticPropsType<typeof getStaticProps>): JSX.Element {
  const tabs = [
    {
      id: "datasets",
      content: group.packages ? (
        <PaginatedDatasetSection
          count={group.package_count || 0}
          datasets={group.packages || []}
          limit={DATASETS_PER_PAGE}
          offset={0}
          name={group.name}
          type="group"
        />
      ) : (
        ""
      ),
      title: "Datasets",
    },
    {
      id: "activity-stream",
      content: (
        <PaginatedActivityStream
          entityId={group._name}
          entityType="group"
          initialActivities={group?.activity_stream ? group.activity_stream : []}
          initialHasMore={group?.activity_stream_has_more || false}
          limit={ACTIVITY_PAGE_SIZE}
        />
      ),
      title: "Activity Stream",
    },
  ];
  return (
    <>
      <Head>
        <title>{group?.name ? group.name : "Org Individual Page"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {group && (
        <Layout>
          <div className="grid grid-rows-datasetpage-hero">
            <section className="row-start-1 row-end-3 col-span-full">
              <div
                className="bg-cover h-full bg-center bg-no-repeat bg-black flex flex-col"
                style={{
                  backgroundImage: "url('/images/backgrounds/SearchHero.avif')",
                }}
              >
                <TopBar />
                <GroupNavCrumbs
                  group={{
                    name: group?.name,
                    title: group?.title,
                  }}
                />
                <div
                  className="grid mx-auto items-center grow custom-container grow"
                  style={{ marginBlock: "8rem" }}
                >
                  <div className="col-span-1">
                    <h1 className="text-6xl font-black text-white">
                      {group.title}
                    </h1>
                  </div>
                </div>
              </div>
            </section>
            <section className="grid row-start-2 row-span-2 col-span-full">
              <div className="custom-container">
                {group && (
                  <main className={styles.main}>
                    <GroupInfo group={group} />
                    <div>
                      <Tabs items={tabs} />
                    </div>
                  </main>
                )}
              </div>
            </section>
          </div>
        </Layout>
      )}
    </>
  );
}
