import { GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";
import OrgNavCrumbs from "@/components/organization/individualPage/OrgNavCrumbs";
import OrgInfo from "@/components/organization/individualPage/OrgInfo";
import Layout from "@/components/_shared/Layout";
import Tabs from "@/components/_shared/Tabs";
import TopBar from "@/components/_shared/TopBar";
import PaginatedActivityStream from "@/components/_shared/PaginatedActivityStream";
import PaginatedDatasetSection from "@/components/_shared/PaginatedDatasetSection";
import { getActivityStreamPage } from "@/lib/queries/activity";
import { trimDatasetCardData } from "@/lib/queries/pageData";
import styles from "styles/DatasetInfo.module.scss";
import { CKAN, Organization } from "@portaljs/ckan";
import { getAllOrganizations, getOrganization } from "@/lib/queries/orgs";
import { searchOrganizationDatasets } from "@/lib/queries/dataset";

const DATASETS_PER_PAGE = 10;
const ACTIVITY_PAGE_SIZE = 20;

export async function getStaticPaths() {
  const paths = (await getAllOrganizations({ detailed: false })).map(
    (org: Organization) => ({
      params: { org: org.name },
    })
  );
  return {
    paths,
    fallback: "blocking",
  };
}

export const getStaticProps: GetStaticProps = async (context) => {
  const DMS = process.env.NEXT_PUBLIC_DMS;
  const ckan = new CKAN(DMS);
  let orgName = context.params?.org as string;
  if (!orgName) {
    return {
      notFound: true,
    };
  }
  orgName = orgName.includes("@") ? orgName.split("@")[1] : orgName;
  let org = await getOrganization({
    name: orgName as string,
  });
  const packageSearch = await searchOrganizationDatasets({
    org: orgName as string,
    offset: 0,
    limit: DATASETS_PER_PAGE,
  });
  org = {
    ...org,
    package_count: packageSearch.count,
    packages: trimDatasetCardData(packageSearch.datasets),
  };
  if (!org) {
    return {
      notFound: true,
    };
  }
  const activityStream = await getActivityStreamPage({
    entityId: org._name,
    entityType: "organization",
    limit: ACTIVITY_PAGE_SIZE,
    offset: 0,
  });
  org = {
    ...org,
    activity_stream: activityStream.activities,
    activity_stream_has_more: activityStream.hasMore,
  };
  return {
    props: {
      org,
    },
    revalidate: 1800,
  };
};

export default function OrgPage({
  org,
}: InferGetStaticPropsType<typeof getStaticProps>): JSX.Element {
  const tabs = [
    {
      id: "datasets",
      content: org.packages ? (
        <PaginatedDatasetSection
          count={org.package_count || 0}
          datasets={org.packages || []}
          limit={DATASETS_PER_PAGE}
          offset={0}
          name={org.name}
          type="organization"
        />
      ) : (
        ""
      ),
      title: "Datasets",
    },
    {
      id: "activity-stream",
      content: (
        <PaginatedActivityStream
          entityId={org._name}
          entityType="organization"
          initialActivities={org?.activity_stream ? org.activity_stream : []}
          initialHasMore={org?.activity_stream_has_more || false}
          limit={ACTIVITY_PAGE_SIZE}
        />
      ),
      title: "Activity Stream",
    },
  ];
  return (
    <>
      <Head>
        <title>{org.title || org.name + " - Organization Page"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {org && (
        <Layout>
          <div className="grid grid-rows-datasetpage-hero">
            <section className="row-start-1 row-end-3 col-span-full">
              <div
                className="bg-cover h-full bg-center bg-no-repeat bg-black flex flex-col"
                style={{
                  backgroundImage: "url('/images/backgrounds/SearchHero.avif')",
                }}
              >
                <TopBar />
                <OrgNavCrumbs
                  org={{
                    name: org?.name,
                    title: org?.title,
                  }}
                />
                <div
                  className="grid mx-auto items-center grow custom-container grow"
                  style={{ marginBlock: "8rem" }}
                >
                  <div className="col-span-1">
                    <h1 className="text-6xl font-black text-white">
                      {org.title}
                    </h1>
                  </div>
                </div>
              </div>
            </section>
            <section className="grid row-start-2 row-span-2 col-span-full">
              <div className="custom-container">
                {org && (
                  <main className={styles.main}>
                    <OrgInfo org={org} />
                    <div>
                      <Tabs items={tabs} />
                    </div>
                  </main>
                )}
              </div>
            </section>
          </div>
        </Layout>
      )}
    </>
  );
}
